<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2019/07/25 00:25:52
sfConfig::add(array(
  'mod_securityauthentication_enabled' => true,
  'mod_securityauthentication_view_class' => 'sfPHP',
));
