<?php
/**
 * Department class file
 */

/**
 * Department
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    orangehrm
 * @subpackage model\admin
 */
class Department extends PluginDepartment
{
}
