<?php

/**
 * PluginDepartment class file
 */

/**
 * PluginDepartment
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    orangehrm
 * @subpackage model\admin\plugin
 */
abstract class PluginDepartment extends BaseDepartment
{

}