<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2019/08/07 17:34:06

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=career.loggcity',
  'username' => 'root',
  'password' => 'thir3a6-i',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
