<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2019/08/08 00:36:15
sfConfig::add(array(
  'mod_securityauthentication_enabled' => true,
  'mod_securityauthentication_view_class' => 'sfPHP',
));
