<?php
// auto-generated by sfSecurityConfigHandler
// date: 2019/08/08 00:36:14
$this->security = array (
  'all' => 
  array (
    'is_secure' => false,
  ),
  'securityauthenticationconfigure' => 
  array (
    'is_secure' => true,
  ),
  'requestpasswordresetcode' => 
  array (
    'is_secure' => true,
  ),
  'resetpassword' => 
  array (
    'is_secure' => true,
  ),
);
